export const LOAD_SHOES_SUCCESS = 'LOAD_SHOES_SUCCESS';
export const CREATE_SHOE_SUCCESS = 'CREATE_SHOE_SUCCESS';
export const UPDATE_SHOE_SUCCESS = 'UPDATE_SHOE_SUCCESS';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';